### ISSUE TITLE
Postman version mentioned in the README is old

### ISSUE THREAD

**Issue by czardoz** [JustGiving/JustGiving.Api.Tools.Postman#5]
The new version (has been out for a long time now) is located here:

https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop

**Comment by pawelsawicz** [comment]
Hey,

Thanks for pointing out this, we going to update this.

**Comment by pawelsawicz** [comment]
Created pull request : https://github.com/JustGiving/JustGiving.Api.Tools.Postman/pull/6 we can close this issue.

**Comment by czardoz** [comment]
Yay, thanks!
